# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'action turnstyle'
description: 'A GitHub Action for serializing workflow runs'
author: 'softprops'
env:
  'GITHUB_TOKEN': 'Repository token provided by Github Actions secrets'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  poll-interval-seconds:
    description: "Number of seconds to wait in between checks for previous run completion (defaults to 60)"
  continue-after-seconds:
    description: "Maximum number of seconds to wait before moving forward (unbound by default)"
  same-branch-only:
    description: "Only wait on other runs from the same branch (defaults to true)"
  wait-for-job:
    description: "Wait for a specific job within the workflow to be complete, instead of the entire workflow"
branding:
  color: 'green'
  icon: 'git-commit'
