# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'action turnstyle'
description: 'A GitHub Action for serializing workflow runs'
author: 'softprops'
env:
  'GITHUB_TOKEN': 'Repository token provided by Github Actions secrets'
runs:
  using: 'node24'
  main: 'dist/index.js'
inputs:
  token:
    description: 'GitHub access token'
    required: false
    default: ${{ github.token }}
  poll-interval-seconds:
    description: "Number of seconds to wait in between checks for previous run completion (defaults to 60)"
  continue-after-seconds:
    description: "Maximum number of seconds to wait before moving forward (unbound by default). Mutually exclusive with abort-after-seconds"
  abort-after-seconds:
    description: "Maximum number of seconds to wait before failing the step (unbound by default). Mutually exclusive with continue-after-seconds"
  same-branch-only:
    description: "Only wait on other runs from the same branch (defaults to true)"
  job-to-wait-for:
    description: "Name of the workflow run's job to wait for (unbound by default)"
  step-to-wait-for:
    description: "Name of the job's step to wait for (unbound by default). Requires job-to-wait-for to be set"
  initial-wait-seconds:
    description: "Total elapsed seconds within which period the action will refresh the list of current runs, if no runs were found in the first poll (0 by default, ie doesn't retry)"
outputs:
  force_continued:
    description: "True if continue-after-seconds is used and the step using turnstyle continued. False otherwise."
branding:
  color: 'green'
  icon: 'git-commit'
