name: main

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "*.md"
    branches:
      - master

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - name: Install
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Build
        run: npm run build
      - name: Check bundled action
        run: git diff --exit-code -- dist/index.js
      - name: Test
        run: npm run test
      - name: Format
        run: npm run fmtcheck

  integration:
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version-file: ".tool-versions"
          cache: "npm"

      - name: Turnstyle
        uses: ./ # Uses an action in the root directory
        with:
          poll-interval-seconds: 10

      - name: Deploy
        run: sleep 180
